networks:
  babeq:
  gpt3_app-shared:
    external: true

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-gpt1
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - gpt1
      # - mysql_db
    networks:
      - babeq
      - gpt3_app-shared
  gpt1:
    container_name: gpt1
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 9000:9000
    networks:
      - babeq
      - gpt3_app-shared
  # mysql_db:
  #   image: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: gpt_db
  #   volumes:
  #     - "./db:/docker-entrypoint-initdb.d"
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - babeq
  #     - gpt3_app-shared
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 9001:80
  #   environment:
  #     - PMA_ARBITRARY=1
  #   networks:
  #     - babeq