version: '3'

networks:
  babeq:
  app-shared:
    driver: bridge
  mysql_db_db-shared:
    external: true

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-gpt3
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gpt3
    networks:
      - babeq
      - app-shared
      - mysql_db_db-shared
  gpt3:
    container_name: gpt3
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8001:9000
    networks:
      - babeq
      - app-shared
      - mysql_db_db-shared